substitutions:
  dev_name: bseed_smart_socket
  bl0937_voltage_divider: "750"
  bl0937_current_resistor: "0.001 ohm"

esphome:
  name: ${dev_name}
bk72xx:
  board: generic-bk7231n-qfn32-tuya
logger:
api:
  reboot_timeout: 0s
ota:
  - platform: esphome
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${dev_name}
captive_portal:
    
status_led:
  pin:
    number: P7

button:
  - platform: restart
    name: ${dev_name}_restart

sensor:
  - platform: hlw8012
    model: BL0937
    cf_pin:
      number: P20
      inverted: True
    cf1_pin:
      number: P8
      inverted: True
    sel_pin:
      number: P9
      inverted: True
    current:
      name: ${dev_name}_current
      accuracy_decimals: 2
    voltage:
      name: ${dev_name}_voltage
      accuracy_decimals: 0
    power:
      name: ${dev_name}_power
      accuracy_decimals: 2
    energy:
      name: ${dev_name}_energy
      accuracy_decimals: 2
    voltage_divider: $bl0937_voltage_divider
    current_resistor: $bl0937_current_resistor
    update_interval: 10s

switch:   
  - platform: template
    name: ${dev_name}_child_lock
    id: child_lock
    icon: "mdi:account-lock"
    entity_category: "config"
    optimistic: True
  - platform: gpio
    name: ${dev_name}_socket_1
    id: ${dev_name}_socket_1
    icon: "mdi:power-socket-de"
    device_class: outlet
    pin: P6
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      output.turn_on: ${dev_name}_led_1
    on_turn_off:
      output.turn_off: ${dev_name}_led_1

output:
  - platform: gpio
    pin: P26
    id: ${dev_name}_led_1
    
binary_sensor:
  - platform: gpio
    pin:
      number: P24
      mode: INPUT_PULLUP
      inverted: True
    id: ${dev_name}_button_1
    on_press:
      - if:
          condition:
            switch.is_off: child_lock
          then:
            switch.toggle: ${dev_name}_socket_1
                
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${dev_name}_ip
      icon: "mdi:lan"
    ssid:
      name: ${dev_name}_ssid
      icon: "mdi:wifi"
    mac_address:
      name: ${dev_name}_mac
      icon: "mdi:lan"
